<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>QS3D.Core</AssemblyName>
    <RootNamespace>QS3D.Core</RootNamespace>
    <Version>0.1.0-preview.10303</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.10303</FileVersion>
    <InformationalVersion>0.1.0-preview.10303</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\external\QS3D-Platform\src\QS3D.Platform.Parity\QS3D.Platform.Parity.csproj" />
  </ItemGroup>
</Project>