#!/usr/bin/env python3
from __future__ import annotations

import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "new-v25-update-manifest.ps1"
HELPER = ROOT / "scripts" / "Qs3dV25UpdateManifestPublicationNative.cs"
source = SCRIPT.read_text(encoding="utf-8")
helper = HELPER.read_text(encoding="utf-8")


def require(text: str, token: str, message: str) -> None:
    if token not in text:
        raise SystemExit(f"ERROR: {message}: missing {token!r}")


# The helper must implement an actual held-handle boundary, not merely expose names
# that make the release script's lexical guard pass.
for token, message in (
    ("CreateFileW", "native generation acquisition is missing"),
    ("SetFileInformationByHandle", "handle-driven rename/delete is missing"),
    ("GetFileInformationByHandle", "stable generation identity is missing"),
    ("GetFinalPathNameByHandleW", "held-handle path verification is missing"),
    ("FileFlagOpenReparsePoint", "reparse-target following is not disabled"),
    ("Flush(true)", "durable held-generation flush is missing"),
    ("OpenOwnedStaging", "owned staging acquisition is missing"),
    ("OpenOwnedExisting", "prior-generation ownership is missing"),
    ("PublishOwnedGeneration", "handle-driven publication is missing"),
    ("GetOwnedGenerationIdentity", "held generation identity API is missing"),
    ("ReadOwnedGenerationBytes", "held exact-byte verification API is missing"),
    ("RollbackOwnedGeneration", "generation-bound rollback API is missing"),
    ("DeleteOwnedGeneration", "generation-bound deletion API is missing"),
):
    require(helper, token, message)


# Exercise the Win32 structure/layout and rename semantics on the hosted Windows
# runner. This is intentionally before the release-script lexical checks so a
# broken native primitive cannot hide behind the expected RED integration state.
if os.name == "nt":
    smoke = r'''
$ErrorActionPreference = 'Stop'
Add-Type -Path $args[0]
$root = Join-Path ([IO.Path]::GetTempPath()) ('qs3d-owned-publish-' + [Guid]::NewGuid().ToString('N'))
[IO.Directory]::CreateDirectory($root) | Out-Null
$stagePath = Join-Path $root 'manifest.tmp'
$outputPath = Join-Path $root 'manifest.json'
$backupPath = Join-Path $root 'manifest.bak'
$stage = $null
$prior = $null
try {
    [IO.File]::WriteAllBytes($outputPath, [Text.Encoding]::UTF8.GetBytes('prior'))
    $stage = [Qs3dV25UpdateManifestPublicationNative]::OpenOwnedStaging($stagePath)
    $prior = [Qs3dV25UpdateManifestPublicationNative]::OpenOwnedExisting($outputPath)
    $payload = [Text.Encoding]::UTF8.GetBytes('{"schemaVersion":2}')
    [Qs3dV25UpdateManifestPublicationNative]::WriteOwnedGeneration($stage, $payload)
    $before = [Qs3dV25UpdateManifestPublicationNative]::GetOwnedGenerationIdentity($stage)
    [Qs3dV25UpdateManifestPublicationNative]::PublishOwnedGeneration($stage, $outputPath, $prior, $backupPath)
    $after = [Qs3dV25UpdateManifestPublicationNative]::GetOwnedGenerationIdentity($stage)
    if ($before -ne $after) { throw 'staging identity changed across held-handle publication' }
    [Qs3dV25UpdateManifestPublicationNative]::AssertOwnedPath($stage, $outputPath)
    $actual = [Qs3dV25UpdateManifestPublicationNative]::ReadOwnedGenerationBytes($stage, 4096)
    if (-not [Linq.Enumerable]::SequenceEqual([byte[]]$payload, [byte[]]$actual)) { throw 'published held bytes differ from generated bytes' }

    [Qs3dV25UpdateManifestPublicationNative]::RollbackOwnedGeneration($stage, $prior, $outputPath, $stagePath)
    [Qs3dV25UpdateManifestPublicationNative]::AssertOwnedPath($prior, $outputPath)
    $restored = [Qs3dV25UpdateManifestPublicationNative]::ReadOwnedGenerationBytes($prior, 4096)
    $expectedPrior = [Text.Encoding]::UTF8.GetBytes('prior')
    if (-not [Linq.Enumerable]::SequenceEqual([byte[]]$expectedPrior, [byte[]]$restored)) { throw 'rollback did not restore exact prior generation bytes' }
}
finally {
    if ($stage) { $stage.Dispose() }
    if ($prior) { $prior.Dispose() }
    if (Test-Path -LiteralPath $root) { Remove-Item -LiteralPath $root -Recurse -Force }
}
'''
    completed = subprocess.run(
        ["pwsh", "-NoLogo", "-NoProfile", "-NonInteractive", "-Command", smoke, str(HELPER)],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="strict",
        check=False,
    )
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip()
        raise SystemExit(f"ERROR: V25 owned-publication native smoke failed: {detail}")


# The production publication block must retain authority over the exact staging
# generation. A pathname that was written, closed, then resolved/reopened is not
# an identity boundary.
for token, message in (
    ("Qs3dV25UpdateManifestPublicationNative", "release script does not load/use owned publication helper"),
    ("OpenOwnedStaging", "staging generation is not held open"),
    ("PublishOwnedGeneration", "publication is not driven by the owned staging handle"),
    ("GetOwnedGenerationIdentity", "published generation identity is not verified from the held handle"),
    ("ReadOwnedGenerationBytes", "published bytes are not verified through the owned generation"),
    ("RollbackOwnedGeneration", "rollback is not bound to owned generation identity"),
):
    require(source, token, message)

publish_anchor = source.find("if ($PSCmdlet.ShouldProcess($outputFull, 'Write QS3D update manifest'))")
if publish_anchor < 0:
    raise SystemExit("ERROR: V25 update-manifest publication block is missing")
publish = source[publish_anchor:]

for unsafe in (
    "[IO.File]::WriteAllText($stagePath",
    "[IO.File]::Move($stage.FullName, $outputFull)",
    "[IO.File]::Replace($stage.FullName, $outputFull",
    "Resolve-OrdinaryNonReparseFile -Path $outputFull -Label 'Published update manifest'",
):
    if unsafe in publish:
        raise SystemExit(f"ERROR: V25 update-manifest publication still reauthorizes by pathname: {unsafe}")

require(source, "$expectedManifestBytes", "expected manifest bytes are not retained for exact verification")
print("PASS: V25 update-manifest publication is generation-owned and path-swap resistant")
