#!/usr/bin/env python3
"""Fail when WPF XAML declares a literal code-behind handler that has no C# method."""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable, List, Sequence, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
ADAPTER_ROOT = ROOT / "src" / "QS3D.BricsCAD.V25"
XAML_NS = "http://schemas.microsoft.com/winfx/2006/xaml"
X_CLASS = f"{{{XAML_NS}}}Class"

IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
CONVENTIONAL_HANDLER_RE = re.compile(r"^On[A-Z][A-Za-z0-9_]*$")
CLASS_DECL_RE_TEMPLATE = r"\b(?:partial\s+)?class\s+{name}\b"

# Common WPF routed/CLR event attribute names. The naming-convention fallback below
# also covers project/custom events whose handler value is a literal OnXxx identifier.
EVENT_ATTRIBUTES: Set[str] = {
    "Activated",
    "AutoGeneratedColumns",
    "AutoGeneratingColumn",
    "BeginningEdit",
    "CanExecute",
    "CellEditEnding",
    "Checked",
    "Click",
    "Closed",
    "Closing",
    "ContentRendered",
    "ContextMenuClosing",
    "ContextMenuOpening",
    "CurrentCellChanged",
    "DataContextChanged",
    "Deactivated",
    "DragEnter",
    "DragLeave",
    "DragOver",
    "Drop",
    "DropDownClosed",
    "DropDownOpened",
    "Executed",
    "GotFocus",
    "GotKeyboardFocus",
    "GotMouseCapture",
    "IsKeyboardFocusWithinChanged",
    "IsMouseCaptureWithinChanged",
    "KeyDown",
    "KeyUp",
    "LayoutUpdated",
    "Loaded",
    "LostFocus",
    "LostKeyboardFocus",
    "LostMouseCapture",
    "ManipulationBoundaryFeedback",
    "ManipulationCompleted",
    "ManipulationDelta",
    "ManipulationInertiaStarting",
    "ManipulationStarted",
    "ManipulationStarting",
    "MediaEnded",
    "MediaFailed",
    "MediaOpened",
    "MouseDoubleClick",
    "MouseDown",
    "MouseEnter",
    "MouseLeave",
    "MouseLeftButtonDown",
    "MouseLeftButtonUp",
    "MouseMove",
    "MouseRightButtonDown",
    "MouseRightButtonUp",
    "MouseUp",
    "MouseWheel",
    "Navigated",
    "Navigating",
    "PasswordChanged",
    "PreparingCellForEdit",
    "PreviewCanExecute",
    "PreviewExecuted",
    "PreviewGotKeyboardFocus",
    "PreviewKeyDown",
    "PreviewKeyUp",
    "PreviewLostKeyboardFocus",
    "PreviewMouseDoubleClick",
    "PreviewMouseDown",
    "PreviewMouseLeftButtonDown",
    "PreviewMouseLeftButtonUp",
    "PreviewMouseMove",
    "PreviewMouseRightButtonDown",
    "PreviewMouseRightButtonUp",
    "PreviewMouseUp",
    "PreviewMouseWheel",
    "RequestNavigate",
    "ScrollChanged",
    "Selected",
    "SelectedItemChanged",
    "SelectionChanged",
    "SizeChanged",
    "Sorting",
    "SourceInitialized",
    "StateChanged",
    "TextChanged",
    "ToolTipClosing",
    "ToolTipOpening",
    "Unchecked",
    "Unloaded",
    "Unselected",
    "ValueChanged",
}

# Literal strings beginning with "On..." in these attributes are data/configuration,
# not code-behind event hookups.
NON_EVENT_LITERAL_ATTRIBUTES: Set[str] = {
    "Class",
    "Command",
    "CommandParameter",
    "Content",
    "DataContext",
    "DisplayMemberPath",
    "Header",
    "Key",
    "Name",
    "Property",
    "SelectedValuePath",
    "Source",
    "Tag",
    "TargetName",
    "Text",
    "ToolTip",
    "Uid",
    "Value",
}


def local_name(xml_name: str) -> str:
    if "}" in xml_name:
        xml_name = xml_name.rsplit("}", 1)[1]
    return xml_name.rsplit(":", 1)[-1]


def strip_csharp_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//[^\r\n]*", "", text)


def method_declaration_pattern(method_name: str) -> re.Pattern[str]:
    # Keep this stricter than a bare "Name(" search so invocations cannot satisfy
    # a missing XAML callback contract.
    return re.compile(
        r"(?m)^\s*"
        r"(?:(?:public|private|protected|internal|static|virtual|override|sealed|"
        r"async|new|partial|extern|unsafe)\s+)*"
        r"(?:[A-Za-z_][A-Za-z0-9_.<>,?\[\]]*\s+)+"
        + re.escape(method_name)
        + r"\s*(?:<[^>{}()]+>)?\s*\("
    )


def literal_handler_bindings(root: ET.Element) -> Iterable[Tuple[str, str, str]]:
    for element in root.iter():
        tag_name = local_name(element.tag)

        if tag_name == "EventSetter":
            handler = element.attrib.get("Handler")
            if handler and IDENTIFIER_RE.fullmatch(handler):
                yield element.attrib.get("Event", "EventSetter"), handler, tag_name

        for raw_attr, raw_value in element.attrib.items():
            attr_name = local_name(raw_attr)
            value = raw_value.strip()
            if not IDENTIFIER_RE.fullmatch(value):
                continue
            if tag_name == "EventSetter" and attr_name in {"Handler", "Event"}:
                continue

            is_known_event = attr_name in EVENT_ATTRIBUTES
            is_conventional_handler = (
                CONVENTIONAL_HANDLER_RE.fullmatch(value) is not None
                and attr_name not in NON_EVENT_LITERAL_ATTRIBUTES
            )
            if is_known_event or is_conventional_handler:
                yield attr_name, value, tag_name


def class_source_files(xaml_path: Path, full_class_name: str) -> List[Path]:
    class_name = full_class_name.rsplit(".", 1)[-1]
    class_decl = re.compile(
        CLASS_DECL_RE_TEMPLATE.format(name=re.escape(class_name))
    )
    result: List[Path] = []
    for path in sorted(xaml_path.parent.glob("*.cs")):
        text = path.read_text(encoding="utf-8-sig")
        if class_decl.search(strip_csharp_comments(text)):
            result.append(path)
    return result


def validate_xaml(xaml_path: Path) -> Tuple[int, List[str]]:
    rel = xaml_path.relative_to(ROOT)
    try:
        tree = ET.parse(xaml_path)
    except ET.ParseError as exc:
        return 0, [f"{rel}: malformed XAML: {exc}"]

    root = tree.getroot()
    full_class_name = root.attrib.get(X_CLASS, "").strip()
    if not full_class_name:
        return 0, []

    sources = class_source_files(xaml_path, full_class_name)
    if not sources:
        return 0, [
            f"{rel}: x:Class={full_class_name!r} has no matching C# class source "
            f"in {xaml_path.parent.relative_to(ROOT)}"
        ]

    source_text = "\n".join(
        strip_csharp_comments(path.read_text(encoding="utf-8-sig"))
        for path in sources
    )

    errors: List[str] = []
    count = 0
    seen: Set[Tuple[str, str, str]] = set()
    for event_name, handler, tag_name in literal_handler_bindings(root):
        binding = (event_name, handler, tag_name)
        if binding in seen:
            continue
        seen.add(binding)
        count += 1
        if method_declaration_pattern(handler).search(source_text):
            continue
        source_names = ", ".join(path.name for path in sources)
        errors.append(
            f'{rel}: <{tag_name}> {event_name}="{handler}" has no method '
            f"declaration in [{source_names}]"
        )
    return count, errors


def main(argv: Sequence[str]) -> int:
    if len(argv) > 1:
        print("usage: preflight-wpf-xaml-event-contract.py", file=sys.stderr)
        return 2
    if not ADAPTER_ROOT.is_dir():
        print(f"FAIL: adapter root not found: {ADAPTER_ROOT.relative_to(ROOT)}")
        return 1

    xaml_files = sorted(ADAPTER_ROOT.rglob("*.xaml"))
    if not xaml_files:
        print(f"FAIL: no XAML files found under {ADAPTER_ROOT.relative_to(ROOT)}")
        return 1

    total_handlers = 0
    errors: List[str] = []
    class_backed_documents = 0
    for xaml_path in xaml_files:
        try:
            parsed_root = ET.parse(xaml_path).getroot()
        except ET.ParseError:
            pass
        else:
            if parsed_root.attrib.get(X_CLASS, "").strip():
                class_backed_documents += 1

        handler_count, file_errors = validate_xaml(xaml_path)
        total_handlers += handler_count
        errors.extend(file_errors)

    if class_backed_documents == 0:
        print("FAIL: no x:Class-backed WPF XAML documents were discovered")
        return 1

    if errors:
        print("FAIL: WPF XAML event-handler contract violations:")
        for error in errors:
            print(f" - {error}")
        return 1

    print(
        "PASS: WPF XAML event-handler contract "
        f"({class_backed_documents} class-backed XAML documents, "
        f"{total_handlers} literal handler bindings)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
