#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "scripts" / "new-v25-update-manifest.ps1"
source = TARGET.read_text(encoding="utf-8")


def require(token: str, message: str) -> None:
    if token not in source:
        raise SystemExit(f"ERROR: {message}: missing {token!r}")


# Publication must retain authority over the exact staging generation. A path that
# was written, closed, then resolved/reopened is not an identity boundary.
for token, message in (
    ("Qs3dV25UpdateManifestPublicationNative", "owned native publication helper is missing"),
    ("OpenOwnedStaging", "staging generation is not held open"),
    ("PublishOwnedGeneration", "publication is not driven by the owned staging handle"),
    ("GetOwnedGenerationIdentity", "published generation identity is not verified from the held handle"),
    ("ReadOwnedGenerationBytes", "published bytes are not verified through the owned generation"),
    ("RollbackOwnedGeneration", "rollback is not bound to owned generation identity"),
):
    require(token, message)

publish_anchor = source.find("if ($PSCmdlet.ShouldProcess($outputFull, 'Write QS3D update manifest'))")
if publish_anchor < 0:
    raise SystemExit("ERROR: V25 update-manifest publication block is missing")
publish = source[publish_anchor:]

for unsafe in (
    "[IO.File]::WriteAllText($stagePath",
    "[IO.File]::Move($stage.FullName, $outputFull)",
    "[IO.File]::Replace($stage.FullName, $outputFull",
    "Resolve-OrdinaryNonReparseFile -Path $outputFull -Label 'Published update manifest'",
):
    if unsafe in publish:
        raise SystemExit(f"ERROR: V25 update-manifest publication still reauthorizes by pathname: {unsafe}")

# Publication must verify exact generated bytes before releasing the owned handle.
require("$expectedManifestBytes", "expected manifest bytes are not retained for exact verification")
require("[Security.Cryptography.CryptographicOperations]::FixedTimeEquals", "published bytes are not compared exactly")

print("PASS: V25 update-manifest publication is generation-owned and path-swap resistant")
