namespace QS3D.Core.SmokeTests
{
    internal static class SmokeTestRegistration
    {
        internal static void RunAll()
        {
            ProjectQuantitySmoke.Run();
            PersistenceHardeningSmoke.Run();
            AdvancedDomainSmoke.Run();
            HardeningRegressionSmoke.Run();
            ReviewHardeningSmoke.Run();
            ContinuationRegressionSmoke.Run();
            LogicRegressionSmoke.Run();
            RevisionRegressionSmoke.Run();
            WorkflowPersistenceSmoke.Run();
            BbsRegressionSmoke.Run();
            WorkflowSafetySmoke.Run();
            CompletionRegressionSmoke.Run();
            SemanticOverflowSmoke.Run();
            RoomBoundaryRegressionSmoke.Run();
            GeometryCompletionSmoke.Run();
            AutoRoomLifecycleSmoke.Run();
            RoomFinishIdentitySmoke.Run();
            RoomFinishHealthSmoke.Run();
            RoomFinishSynchronizationSmoke.Run();
            LinearRebarLayoutSmoke.Run();
            WallJunctionRegressionSmoke.Run();
            WallJunctionAdjustmentSmoke.Run();
            PolylineOpeningCutSmoke.Run();
            ProjectRebarShapeSmoke.Run();
            RebarOwnershipHealthSmoke.Run();
            RebarFabricationQualificationSmoke.Run();
            GeneratedGeometryStaleSmoke.Run();
            CurtainWallLayoutSmoke.Run();
            WallPierProfileSmoke.Run();
            CurtainWallDetailSmoke.Run();
            GeneratedOutputHealthStaleSmoke.Run();
            CurtainFrameOpeningSmoke.Run();
            CurtainFrameOpeningHealthSmoke.Run();
            BomReleaseGuardSmoke.Run();
            LevelReferenceSmoke.Run();
            GridNamingSmoke.Run();
            GridNamingHealthSmoke.Run();
            GridIntersectionPlannerSmoke.Run();
            GridSpatialOrderingSmoke.Run();
            PolygonScanlineClipperSmoke.Run();
            SemanticTagRendererSmoke.Run();
            SemanticDocumentationTableSmoke.Run();
            ProjectInterchangeJsonSmoke.Run();
            RegenerationSubsetSmoke.Run();
            GeneratedHandleOwnershipIndexSmoke.Run();
            DependencyGraphDirectDependentsSmoke.Run();
            ProjectStateLookupSmoke.Run();
            SelectionStateSmoke.Run();
            BulkEditCanonicalizationSmoke.Run();
            RegenerationAtomicitySmoke.Run();
            HostLinkCanonicalizationSmoke.Run();
            ProjectSessionAuditSmoke.Run();
            ProjectInterchangeValidationSmoke.Run();
            QsdbSaveAtomicitySmoke.Run();
            AuditTrailSnapshotSmoke.Run();
        }
    }
}
